Add various functions for working with `CFTypeRef`s
dcuddeback/core-foundation-sys pull request #4
Opened 2016-10-03 19:57 UTC by burtonageo

2016-10-15 17:30 UTC, dcuddeback requested changes

2016-10-15 17:30 UTC, dcuddeback commented on src/base.rs
> +    pub fn CFMakeCollectible(cf: CFTypeRef) -> CFTypeRef;
Typo: `CFMakeCollectable` (with an "a" instead of an "i").

2016-10-15 17:30 UTC, dcuddeback commented on src/base.rs
> +    pub fn CFCopyTypeIDDescription(cf: CFTypeRef) -> CFStringRef;
I see `CFTypeId` for the function argument instead of `CFTypeRef`:

```c
CFStringRef CFCopyTypeIDDescription(CFTypeID type_id);
```

2016-10-15 17:30 UTC, dcuddeback commented on src/base.rs
> +    pub fn CFShow(obj: CFTypeRef);
I don't see this function in `CFBase.h`. Is it defined somewhere else?

2016-10-15 17:43 UTC, dcuddeback commented on src/base.rs
> +    pub fn CFShow(obj: CFTypeRef);
Looks like it's defined in `CFString.h`. Do you mind moving it to `src/string.rs`?

2016-10-17 20:50 UTC, burtonageo commented
All done, thanks 👍

2017-03-05 02:57 UTC, dcuddeback commented on src/string.rs
> +    pub fn CFGetTypeID(cf: CFTypeRef) -> CFTypeID;
These three functions are defined in `CFBase.h`. Can we define them in `src/base.rs` to keep the file mapping consistent?

2017-03-19 00:26 UTC, dcuddeback requested changes

2017-03-19 00:26 UTC, dcuddeback commented on src/base.rs
> +    pub fn CFAutorelease(arg: CFTypeRef) -> CFTypeID;
This returns `CFTypeRef`:

```c
CF_EXPORT
CFTypeRef CFAutorelease(CFTypeRef CF_RELEASES_ARGUMENT arg) CF_AVAILABLE(10_9, 7_0);
```

Is `CF_RELEASES_ARGUMENT` something we need to worry about?

2017-03-19 00:26 UTC, dcuddeback commented on src/base.rs
> +pub type CFAllocatorPreferredSizeCallBack = extern "C" fn(size: CFIndex, hint: CFOptionFlags, info: *mut c_void) -> CFIndex;
There were some merge conflicts here. I took the definitions from your previous PR.

2017-03-27 20:58 UTC, burtonageo commented on src/base.rs
> +    pub fn CFAutorelease(arg: CFTypeRef) -> CFTypeID;
I don't think it is - it looks like it's an attribute to say that an argument is sent a `release` message when the function is called (https://clang-analyzer.llvm.org/annotations.html).

2017-03-27 20:58 UTC, burtonageo commented on src/base.rs
> +pub type CFAllocatorPreferredSizeCallBack = extern "C" fn(size: CFIndex, hint: CFOptionFlags, info: *mut c_void) -> CFIndex;
Thanks :-)

2017-11-12 17:24 UTC, dcuddeback commented on src/base.rs
> +    pub fn CFAutorelease(arg: CFTypeRef) -> CFTypeID;
Thanks for the link. Looks like it's just a hint to the static analyzer and doesn't affect functionality of the compiled code.

2017-11-12 17:28 UTC, dcuddeback commented
@burtonageo I merged this on the command-line, because there was one more function definition that needed fixing. `CFAllocatorCreate` returns `CFAllocatorRef` instead of `CFAllocatorContext`. I took care of that when merging.

Thanks for sending the PR. I'm about to make a new release that will include all of your contributions.

2017-11-12 17:28 UTC, closed without merging