Add CFSet
dcuddeback/core-foundation-sys pull request #5
Opened 2016-10-03 19:58 UTC by burtonageo

2016-10-15 18:24 UTC, dcuddeback requested changes
Thanks @burtonageo. I left a few line comments for things that don't match the library's header files.

2016-10-15 18:24 UTC, dcuddeback commented on src/set.rs
> +pub type CFSetRetainCallBack = extern "C" fn(allocator: CFAllocatorRef, value: *const c_void);
This function returns `const void *`:

``` c
typedef const void *    (*CFSetRetainCallBack)(CFAllocatorRef allocator, const void *value);
```

2016-10-15 18:24 UTC, dcuddeback commented on src/set.rs
> +    pub fn CFSetCreateMutableCopy(allocator: CFAllocatorRef, capacity: CFIndex, theSet: CFSetRef) -> CFSetRef;
This function returns `CFMutableSetRef`:

```c
CFMutableSetRef CFSetCreateMutableCopy(CFAllocatorRef allocator, CFIndex capacity, CFSetRef theSet);
```

2016-10-15 18:24 UTC, dcuddeback commented on src/set.rs
> +    pub fn CFSetGetValueIfPresent(theSet: CFSetRef, candidate: *const c_void, value: *const *mut c_void) -> Boolean;
`const` and `mut` should be reversed here. `value` is an out-parameter that will be written to with a value of a `*const c_void`.

2016-10-15 18:24 UTC, dcuddeback commented on src/set.rs
> +    pub fn CFSetCreate(allocator: CFAllocatorRef, values: *const *mut c_void, numValues: CFIndex,
`const` and `mut` should be reversed here, too. The parameter is defined as `const void **values`, which is a mutable pointer to a const pointer.

2016-10-15 18:24 UTC, dcuddeback commented on src/set.rs
> +    pub fn CFSetGetValues(theSet: CFSetRef, values: *const *mut c_void);
Here too, `values` is an out-parameter so should be `*mut *const c_void`.

2016-10-15 18:24 UTC, dcuddeback commented on src/set.rs
> +    pub fn CFSetRemoveValue(theSet: CFMutableSetRef, value: *const *mut c_void);
`value` is just a single pointer: `*const c_void`:

```c
void CFSetRemoveValue(CFMutableSetRef theSet, const void *value);
```

2016-10-17 20:57 UTC, burtonageo commented
All done, thanks. Sorry - I sometimes get my C pointer syntax confused 😄

2017-03-05 02:50 UTC, dcuddeback approved these changes

2017-03-05 02:53 UTC, merged